apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  labels:
    app: mysql
    app.kubernetes.io/name: mysql
data:
  my.cnf: |
    [mysqld]
    !includedir /etc/mysql/conf.d/


  # log-bin=mysql-bin
  # max_binlog_size=1G
  # expire_logs_days=30

  # initdb.sql: |
  #   SET GLOBAL binlog_format = 'ROW';
  #   SET GLOBAL server_id = 184054;
  #   CREATE DATABASE test;
  #   use test;
  #   CREATE TABLE example (id INT(16) NOT NULL, name VARCHAR(32));
  #   INSERT INTO example VALUES (123, 'tmax');


  primary.cnf: |
    # Apply this config only on the primary.
    [mysqld]
    log-bin
    gtid_mode=ON
    enforce_gtid_consistency=ON
  replica.cnf: |
    # Apply this config only on replicas.
    [mysqld]
    gtid_mode=ON
    enforce_gtid_consistency=ON
    super-read-only
    log_bin=OFF