apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: member-sink-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster3
spec:
  class: io.confluent.connect.jdbc.JdbcSinkConnector
  tasksMax: 1
  config:
    topics: member-service-v1.member.member
    connection.url: "jdbc:mysql://mysql-all-svc.default.svc.cluster.local:3306/all"
    connection.user: "root"
    connection.password: "1234"
    auto.create: false
    auto.evolve: false
    insert.mode: "upsert"
    pk.mode: "record_key"
    pk.fields: member_id
    tombstones.on.delete: "true"
    delete.enabled: "true"
    # pk.mode: "record_key"
    # topics.regex: dbserver1.member.(.*)
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: true

    transforms: unwrap, route
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    transforms.route.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.route.regex: "([^.]+)\\.([^.]+)\\.([^.]+)"
    transforms.route.replacement: $3
