apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: respondent-source-connector
  namespace: kafka
  labels:
    strimzi.io/cluster: kafka-connect-cluster3
spec:
  class: io.debezium.connector.mysql.MySqlConnector
  tasksMax: 1
  config:
    tasks.max: 1
    database.hostname: respondent.jeonggyu-namespace.svc.cluster.local
    database.port: 3306
    database.user: root
    database.password: ""
    database.server.id: 184054
    database.server.name: dbserver1
    topic.prefix: respondent
    database.include.list: respondent
    # table.whitelist: member
    topic.creation.default.partitions: 1
    topic.creation.default.replication.factor: 1
    database.allowPublicKeyRetrieval: true
    database.history.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
    database.history.kafka.topic: dbhistory.respondent
    schema.history.internal.kafka.bootstrap.servers: kafka-cluster-kafka-bootstrap:9092
    schema.history.internal.kafka.topic: schema-changes.respondent
    snapshot.mode: schema_only
    include.schema.changes: true
    key.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: true
    value.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter.schemas.enable: true

    # transforms: unwrap,addTopicPrefix,route
    # transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    # transforms.unwrap.drop.tombstones: false
    # transforms.unwrap.delete.handling.mode: rewrite
    # transforms.unwrap.add.fields: op,schema

    # transforms: timestamp
    transforms: unwrap,addTopicPrefix
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.drop.tombstones: false
    transforms.addTopicPrefix.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.addTopicPrefix.regex: "(.*)"
    transforms.addTopicPrefix.replacement: $1

    # transforms.timestamp.type: org.apache.kafka.connect.transforms.TimestampConverter$Value
    # transforms.timestamp.target.type: Timestamp
    # transforms.timestamp.field: upload_date
    # transforms.timestamp.format: "yyyy-MM-dd HH:mm:ss"
    # time.precision.mode: connect
    # enable.time.adjuster: "false"
