apiVersion: v1
kind: Pod
metadata:
  name: post-springboot-pod # Service 이름
  labels:
    app: post-springboot-pod # Pod 이름
spec:
  containers:
    - name: post-springboot-app
      # 도커 이미지를 push한 ECR의 엔드포인트
      image: lmslmsms0616/kube_msa_post_service
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: post-springboot-svc
spec:
  selector:
    app: post-springboot-pod # Pod 이름
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: NodePort
